<?php
/*
 * Copyright (C) 2013, HealthCare IT, Inc. - All Rights Reserved
 * Unauthorized copying or redistribution of this file in source and binary forms via any medium is strictly prohibited
 * Proprietary and confidential
 */

define('CACURE_X_SETTINGS_DEFAULT_REDIRECT', 'cacure_x_form_default_redirect');
define('CACURE_X_SETTINGS_COMPLETED_REDIRECT', 'cacure_x_form_completed_redirect');
define('CACURE_X_SETTINGS_COMPLETED_MESSAGE', 'cacure_x_form_completed_message');

define('CACURE_X_FORMS_STATUS_NEW', 'new');
define('CACURE_X_FORMS_STATUS_IN_PROGRESS', 'in-progress');
define('CACURE_X_FORMS_STATUS_SUBMITTED', 'submitted');
define('CACURE_X_FORMS_STATUS_COMPLETED', 'completed');

function cacure_x_preprocess_html(&$vars){
  $args = arg();
  if ($args[0] == 'form') {
    $cacure_x = drupal_get_path('module', 'cacure_x');
    drupal_add_css($cacure_x . '/xsltforms/xforms_main.css', 'file');
    drupal_add_js($cacure_x.'/xsltforms/dialog_box.js', 'file');
    drupal_add_js($cacure_x.'/xsltforms/xsltforms.js', 'file');
    drupal_add_js($cacure_x.'/js/forms-page.js', 'file');

    if (strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE')) {
      drupal_add_js($cacure_x . '/js/chrome-frame.js', 'file');
      drupal_add_js("var url = location.protocol + '//' + location.host + '/';
        // You may want to place these lines inside an onload handler
        CFInstall.check({
          mode: \"overlay\",
          destination: url
        })", 'inline');
    }
  }
}

 /**
 * Implementation of hook_menu().
 */
function cacure_x_menu() {
  $items = array();

  $items['admin/config/cacure_settings/xforms'] = array(
    'title' => 'XForms module settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cacure_x_settings_page'),
    'access callback'  => 'cacure_x_settings_access',
    'type' => MENU_LOCAL_TASK,
  );

  $items['form/%/%/%'] = array(
    'title' => 'Questionnaire',
    'page callback' => 'cacure_x_page_callback',
    'page arguments' => array(1,2,3),
    'access callback'  => 'user_is_logged_in',
    'file' => 'cacure_x.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['formsubmit/%/%/%/%/%'] = array(
    'title' => 'Questionnaire',
    'page callback' => 'cacure_x_formsubmit_callback',
    'page arguments' => array(1,2,3,4,5),
    'access callback'  => 'user_is_logged_in',
    'file' => 'cacure_x.pages.inc',
    'type' => MENU_CALLBACK,
  );

  $items['formsubmit/%/%/%/%/%/%'] = array(
    'title' => 'Questionnaire',
    'page callback' => 'cacure_x_formsubmit_callback',
    'page arguments' => array(1,2,3,4,5,6),
    'access callback'  => 'user_is_logged_in',
    'file' => 'cacure_x.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function cacure_x_settings_access() {
  global $user;
  if (in_array('administrator', $user->roles)) {
    return true;
  }
  return false;
}

function cacure_x_settings_page($form, $form_state) {
  $form = array();

  $defaultRedirect = variable_get(CACURE_X_SETTINGS_DEFAULT_REDIRECT, null);
  $completedRedirect = variable_get(CACURE_X_SETTINGS_COMPLETED_REDIRECT, null);
  $completedMessage = variable_get(CACURE_X_SETTINGS_COMPLETED_MESSAGE, null);

  $form[CACURE_X_SETTINGS_DEFAULT_REDIRECT] = array(
    '#type' => 'textfield',
    '#title' => 'After single form is saved redirect',
    '#default_value' => $defaultRedirect
  );

  $form[CACURE_X_SETTINGS_COMPLETED_REDIRECT] = array(
    '#type' => 'textfield',
    '#title' => 'After all forms completed redirect',
    '#default_value' => $completedRedirect
  );

  $form[CACURE_X_SETTINGS_COMPLETED_MESSAGE] = array(
    '#type' => 'textarea',
    '#title' => 'After all forms completed message',
    '#default_value' => $completedMessage,
    '#description' => 'Leave blank if no message needed.'
  );

  return system_settings_form($form);
}

function cacure_x_set_redirect($path) {
  $_SESSION['cure_xforms_redirect'] = $path;
}

function cacure_x_get_redirect() {
  return !empty($_SESSION['cure_xforms_redirect']) ? $_SESSION['cure_xforms_redirect'] : '';
}

function cacure_x_set_form_completed_redirect($path) {
  $_SESSION['cure_xforms_completed_redirect'] = $path;
}

function cacure_x_get_form_completed_redirect() {
  return !empty($_SESSION['cure_xforms_completed_redirect']) ? $_SESSION['cure_xforms_completed_redirect'] : '';
}

function cacure_x_form_statuses() {
  return array(
    CACURE_X_FORMS_STATUS_NEW => 1,
    CACURE_X_FORMS_STATUS_IN_PROGRESS => 2,
    CACURE_X_FORMS_STATUS_SUBMITTED => 3,
    CACURE_X_FORMS_STATUS_COMPLETED => 4
  );
}
