/*******************************************************************************
 * Copyright (C) 2013 HealthCare IT, Inc. - All Rights Reserved
 * Unauthorized copying or redistribution of this file in source and binary forms via any medium is strictly prohibited
 * Proprietary and confidential
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.10 at 05:08:13 PM EST 
//


package com.healthcit.cacure.security;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for entityTagPermissions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entityTagPermissions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="formTagPermissions" type="{http://www.healthcit.com/CollectorSecurity}formTagPermissions" minOccurs="0"/>
 *         &lt;element name="moduleTagPermissions" type="{http://www.healthcit.com/CollectorSecurity}moduleTagPermissions" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="entityId" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entityTagPermissions", propOrder = {
    "formTagPermissions",
    "moduleTagPermissions"
})
public class EntityTagPermissions {

    protected FormTagPermissions formTagPermissions;
    protected ModuleTagPermissions moduleTagPermissions;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String entityId;

    /**
     * Gets the value of the formTagPermissions property.
     * 
     * @return
     *     possible object is
     *     {@link FormTagPermissions }
     *     
     */
    public FormTagPermissions getFormTagPermissions() {
        return formTagPermissions;
    }

    /**
     * Sets the value of the formTagPermissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormTagPermissions }
     *     
     */
    public void setFormTagPermissions(FormTagPermissions value) {
        this.formTagPermissions = value;
    }

    /**
     * Gets the value of the moduleTagPermissions property.
     * 
     * @return
     *     possible object is
     *     {@link ModuleTagPermissions }
     *     
     */
    public ModuleTagPermissions getModuleTagPermissions() {
        return moduleTagPermissions;
    }

    /**
     * Sets the value of the moduleTagPermissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModuleTagPermissions }
     *     
     */
    public void setModuleTagPermissions(ModuleTagPermissions value) {
        this.moduleTagPermissions = value;
    }

    /**
     * Gets the value of the entityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityId() {
        return entityId;
    }

    /**
     * Sets the value of the entityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityId(String value) {
        this.entityId = value;
    }

}
