<?php

function my_menu_refresh_menu() {
  $items = array();

  $items['admin/config/refresh_menu'] = array(
    'title' => 'Menu refresh',
    'description' => 'Menu refresh',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('my_menu_refresh_admin_form'),
    'access arguments' => array('administrator')
  );

  return $items;
}

function my_menu_refresh_admin_form($form, $form_state) {
  $form = array();
  $form['refresh'] = array(
    '#type' => 'submit',
    '#value' => t('Refresh menu'),
    '#name' => 'refresh'
  );
  return $form;
}

function my_menu_refresh_admin_form_submit($form, $form_state) {
  $op = $form_state['triggering_element']['#name'];
  if ($op == 'refresh') {
    if (menu_rebuild()) {
      drupal_set_message(t('Menu was refreshed successfully'));
    }
  }
}