
@echo off

set JOBRUN_DIR=D:\
set JOBRUN_FOLDER=INTEGRATION\PENTAHO\
set JOB_DIR=%JOBRUN_DIR%%JOBRUN_FOLDER%

SET JOB_FOLDER=cure_etl
SET JOB_DATA_FOLDER="D:\INTEGRATION\PENTAHO\cure_etl\DATA\"

REM Main Process of this bat file
del /Q %JOB_DATA_FOLDER%CONVERTED\*.*
del /Q %JOB_DATA_FOLDER%COUCH-DATA\*.*
del /Q %JOB_DATA_FOLDER%ERROR\*.*
del /Q %JOB_DATA_FOLDER%INVALID-DATA\*.*
del /Q %JOB_DATA_FOLDER%INVALID-XML\*.*
del /Q %JOB_DATA_FOLDER%PRE_PROCESSED\*.*
del /Q %JOB_DATA_FOLDER%PROCESSED\*.*
del /Q %JOB_DATA_FOLDER%SPLIT-XML\*.*
del /Q %JOB_DATA_FOLDER%TARGET-XML\*.*
del /Q %JOB_DATA_FOLDER%TMP\*.*
del /Q %JOB_DATA_FOLDER%UN_PROCESSED\*.*
del /Q %JOB_DATA_FOLDER%VALID-DATA\*.*
del /Q %JOB_DATA_FOLDER%VALID-XML\*.*

REM Post process
REM cd \d %JOB_DIR%\%JOB_FOLDER%\BAT
