/*******************************************************************************
 * Copyright (C) 2013 HealthCare IT, Inc. - All Rights Reserved
 * Unauthorized copying or redistribution of this file in source and binary forms via any medium is strictly prohibited
 * Proprietary and confidential
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.19 at 12:09:44 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.healthcit.com/FormDataModel", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.healthcit.cacure.xforms.model;
