//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.06 at 03:59:27 PM EDT 
//


package com.healthcit.cacure.metadata.module;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FormInstanceCollectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormInstanceCollectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="instance" type="{http://www.healthcit.com/ModuleMetadata}FormInstanceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="availableParentInstances" type="{http://www.healthcit.com/ModuleMetadata}AvailableParentInstanceCollectionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="maxInstances" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="existingInstances" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="instanceGroup" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormInstanceCollectionType", propOrder = {
    "instance",
    "availableParentInstances"
})
public class FormInstanceCollectionType {

    protected List<FormInstanceType> instance;
    protected AvailableParentInstanceCollectionType availableParentInstances;
    @XmlAttribute(required = true)
    protected long maxInstances;
    @XmlAttribute
    protected Long existingInstances;
    @XmlAttribute
    protected String instanceGroup;

    /**
     * Gets the value of the instance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormInstanceType }
     * 
     * 
     */
    public List<FormInstanceType> getInstance() {
        if (instance == null) {
            instance = new ArrayList<FormInstanceType>();
        }
        return this.instance;
    }

    /**
     * Gets the value of the availableParentInstances property.
     * 
     * @return
     *     possible object is
     *     {@link AvailableParentInstanceCollectionType }
     *     
     */
    public AvailableParentInstanceCollectionType getAvailableParentInstances() {
        return availableParentInstances;
    }

    /**
     * Sets the value of the availableParentInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailableParentInstanceCollectionType }
     *     
     */
    public void setAvailableParentInstances(AvailableParentInstanceCollectionType value) {
        this.availableParentInstances = value;
    }

    /**
     * Gets the value of the maxInstances property.
     * 
     */
    public long getMaxInstances() {
        return maxInstances;
    }

    /**
     * Sets the value of the maxInstances property.
     * 
     */
    public void setMaxInstances(long value) {
        this.maxInstances = value;
    }

    /**
     * Gets the value of the existingInstances property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getExistingInstances() {
        return existingInstances;
    }

    /**
     * Sets the value of the existingInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setExistingInstances(Long value) {
        this.existingInstances = value;
    }

    /**
     * Gets the value of the instanceGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceGroup() {
        return instanceGroup;
    }

    /**
     * Sets the value of the instanceGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceGroup(String value) {
        this.instanceGroup = value;
    }

}
