//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.06 at 03:59:27 PM EDT 
//


package com.healthcit.cacure.metadata.module;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.healthcit.cacure.metadata.module package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Modules_QNAME = new QName("http://www.healthcit.com/ModuleMetadata", "modules");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.healthcit.cacure.metadata.module
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SkipRuleType }
     * 
     */
    public SkipRuleType createSkipRuleType() {
        return new SkipRuleType();
    }

    /**
     * Create an instance of {@link FormInstanceType }
     * 
     */
    public FormInstanceType createFormInstanceType() {
        return new FormInstanceType();
    }

    /**
     * Create an instance of {@link ModuleType }
     * 
     */
    public ModuleType createModuleType() {
        return new ModuleType();
    }

    /**
     * Create an instance of {@link AvailableParentInstanceType }
     * 
     */
    public AvailableParentInstanceType createAvailableParentInstanceType() {
        return new AvailableParentInstanceType();
    }

    /**
     * Create an instance of {@link FormType }
     * 
     */
    public FormType createFormType() {
        return new FormType();
    }

    /**
     * Create an instance of {@link AvailableParentInstanceCollectionType }
     * 
     */
    public AvailableParentInstanceCollectionType createAvailableParentInstanceCollectionType() {
        return new AvailableParentInstanceCollectionType();
    }

    /**
     * Create an instance of {@link FormInstanceCollectionType }
     * 
     */
    public FormInstanceCollectionType createFormInstanceCollectionType() {
        return new FormInstanceCollectionType();
    }

    /**
     * Create an instance of {@link ModuleCollectionType }
     * 
     */
    public ModuleCollectionType createModuleCollectionType() {
        return new ModuleCollectionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModuleCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.healthcit.com/ModuleMetadata", name = "modules")
    public JAXBElement<ModuleCollectionType> createModules(ModuleCollectionType value) {
        return new JAXBElement<ModuleCollectionType>(_Modules_QNAME, ModuleCollectionType.class, null, value);
    }

}
