//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.06 at 03:59:27 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.healthcit.com/ModuleMetadata", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.healthcit.cacure.metadata.module;
